<a href="https://colab.research.google.com/github/2303A51923/PDS/blob/main/Lab_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv("healthcare_dataset.csv")
print("Dataset before cleaning:")
print(df.head(10))
invalid_ages = df[(df['Age'] < 0) | (df['Age'] > 120)]
print("\nInvalid Ages Found:")
print(invalid_ages)
df_cleaned = df[(df['Age'] >= 0) & (df['Age'] <= 120)]

print("\nDataset after cleaning:")
print(df_cleaned.head(10))
df_cleaned.to_csv("healthcare_dataset_cleaned.csv", index=False)

Dataset before cleaning:
                 Name  Age  Gender Blood Type Medical Condition  \
0       Bobby JacksOn   30    Male         B-            Cancer
1        LesLie TErRy   62    Male         A+           Obesity
2         DaNnY sMitH   76  Female         A-           Obesity
3        andrEw waTtS   28  Female         O+          Diabetes
4       adrIENNE bEll   43  Female        AB+            Cancer
5       EMILY JOHNSOn   36    Male         A+            Asthma
6      edwArD EDWaRDs   21  Female        AB-          Diabetes
7  CHrisTInA MARtinez   20  Female         A+            Cancer
8     JASmINe aGuIlaR   82    Male        AB+            Asthma
9    ChRISTopher BerG   58  Female        AB-            Cancer

  Date of Admission            Doctor                     Hospital  \
0        2024-01-31     Matthew Smith              Sons and Miller
1        2019-08-20   Samantha Davies                      Kim Inc
2        2022-09-22  Tiffany Mitchell                     Cook PLC
3        2020-11-18       Kevin Wells   Hernandez Rogers and Vang,
4        2022-09-19    Kathleen Hanna                  White-White
5        2023-12-20     Taylor Newton               Nunez-Humphrey
6        2020-11-03       Kelly Olson              Group Middleton
7        2021-12-28    Suzanne Thomas  Powell Robinson and Valdez,
8        2020-07-01   Daniel Ferguson                Sons Rich and
9        2021-05-23       Heather Day               Padilla-Walker

  Insurance Provider  Billing Amount  Room Number Admission Type  \
0         Blue Cross    18856.281306          328         Urgent
1           Medicare    33643.327287          265      Emergency
2              Aetna    27955.096079          205      Emergency
3           Medicare    37909.782410          450       Elective
4              Aetna    14238.317814          458         Urgent
5   UnitedHealthcare    48145.110951          389         Urgent
6           Medicare    19580.872345          389      Emergency
7              Cigna    45820.462722          277      Emergency
8              Cigna    50119.222792          316       Elective
9   UnitedHealthcare    19784.631062          249       Elective

  Discharge Date   Medication  Test Results
0     2024-02-02  Paracetamol        Normal
1     2019-08-26    Ibuprofen  Inconclusive
2     2022-10-07      Aspirin        Normal
3     2020-12-18    Ibuprofen      Abnormal
4     2022-10-09   Penicillin      Abnormal
5     2023-12-24    Ibuprofen        Normal
6     2020-11-15  Paracetamol  Inconclusive
7     2022-01-07  Paracetamol  Inconclusive
8     2020-07-14      Aspirin      Abnormal
9     2021-06-22  Paracetamol  Inconclusive

Invalid Ages Found:
Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

Dataset after cleaning:
                 Name  Age  Gender Blood Type Medical Condition  \
0       Bobby JacksOn   30    Male         B-            Cancer
1        LesLie TErRy   62    Male         A+           Obesity
2         DaNnY sMitH   76  Female         A-           Obesity
3        andrEw waTtS   28  Female         O+          Diabetes
4       adrIENNE bEll   43  Female        AB+            Cancer
5       EMILY JOHNSOn   36    Male         A+            Asthma
6      edwArD EDWaRDs   21  Female        AB-          Diabetes
7  CHrisTInA MARtinez   20  Female         A+            Cancer
8     JASmINe aGuIlaR   82    Male        AB+            Asthma
9    ChRISTopher BerG   58  Female        AB-            Cancer

  Date of Admission            Doctor                     Hospital  \
0        2024-01-31     Matthew Smith              Sons and Miller
1        2019-08-20   Samantha Davies                      Kim Inc
2        2022-09-22  Tiffany Mitchell                     Cook PLC
3        2020-11-18       Kevin Wells   Hernandez Rogers and Vang,
4        2022-09-19    Kathleen Hanna                  White-White
5        2023-12-20     Taylor Newton               Nunez-Humphrey
6        2020-11-03       Kelly Olson              Group Middleton
7        2021-12-28    Suzanne Thomas  Powell Robinson and Valdez,
8        2020-07-01   Daniel Ferguson                Sons Rich and
9        2021-05-23       Heather Day               Padilla-Walker

  Insurance Provider  Billing Amount  Room Number Admission Type  \
0         Blue Cross    18856.281306          328         Urgent
1           Medicare    33643.327287          265      Emergency
2              Aetna    27955.096079          205      Emergency
3           Medicare    37909.782410          450       Elective
4              Aetna    14238.317814          458         Urgent
5   UnitedHealthcare    48145.110951          389         Urgent
6           Medicare    19580.872345          389      Emergency
7              Cigna    45820.462722          277      Emergency
8              Cigna    50119.222792          316       Elective
9   UnitedHealthcare    19784.631062          249       Elective

  Discharge Date   Medication  Test Results
0     2024-02-02  Paracetamol        Normal
1     2019-08-26    Ibuprofen  Inconclusive
2     2022-10-07      Aspirin        Normal
3     2020-12-18    Ibuprofen      Abnormal
4     2022-10-09   Penicillin      Abnormal
5     2023-12-24    Ibuprofen        Normal
6     2020-11-15  Paracetamol  Inconclusive
7     2022-01-07  Paracetamol  Inconclusive
8     2020-07-14      Aspirin      Abnormal
9     2021-06-22  Paracetamol  Inconclusive

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
df = pd.read_csv("bank.csv")
print("Original Dataset (first 5 rows):")
display(df.head())

print("\nAvailable Columns:", df.columns)
income_column = "balance"
df['Income_Normalized'] = MinMaxScaler().fit_transform(df[[income_column]])
df['Income_Standardized'] = StandardScaler().fit_transform(df[[income_column]])

print("\nDataset After Scaling (first 5 rows):")
display(df[[income_column, "Income_Normalized", "Income_Standardized"]].head())
df.to_csv("bank_scaled.csv", index=False)
print("\n✅ Scaled dataset saved as 'bank_scaled.csv'")

Original Dataset (first 5 rows):

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

Available Columns: Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

Dataset After Scaling (first 5 rows):

   balance  Income_Normalized  Income_Standardized
0     2343           0.104371             0.252525
1       45           0.078273            -0.459974
2     1270           0.092185            -0.080160
3     2476           0.105882             0.293762
4      184           0.079851            -0.416876

✅ Scaled dataset saved as 'bank_scaled.csv'